[package]
name = "waluna-back"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors", "fs"] }
reqwest = { version = "0.11", features = ["json"] }
librqbit = "8.1.1"
chrono = "0.4"
nyaa-si = "0.3.0"

[[bin]]
name = "waluna-back"
path = "src/main.rs"

[[bin]]
name = "example"
path = "src/bin/example.rs"

[[bin]]
name = "client_example"
path = "src/bin/client_example.rs"

[[bin]]
name = "nyaa_example"
path = "src/bin/nyaa_example.rs"
