[package]
name = "waluna-back"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
tower = "0.5.2"
tower-http = { version = "0.5", features = ["trace", "cors", "fs"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-socks = "0.5"
tokio-native-tls = "0.3"
librqbit = "8.1.1"
chrono = "0.4"
nyaa-si = "0.3.0"
walkdir = "2"
futures = "0.3"
scraper = "0.25.0"
unicode-normalization = "0.1.25"
regex = "1.12.2"
hyper = "1.8.1"
lazy_static = "1.5.0"
governor = "0.10"

[[bin]]
name = "waluna-back"
path = "src/main.rs"
